=== cessda/cessda.cmv.core/src/test/resources/eu.cessda.cmv.core.mediatype.validationreport.v0.xml.JaxbValidationReportV0Test/validation-report-v0.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:complexType name="ValidationReportType">
      <xsd:sequence>
         <xsd:element name="ConstraintViolation" type="ConstraintViolationType" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="ConstraintViolationType">
      <xsd:sequence>
         <xsd:element name="Message" type="xsd:string"/>
         <xsd:element name="LocationInfo" type="LocationInfoType" minOccurs="0"/>
      </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="LocationInfoType">
      <xsd:sequence>
         <xsd:element name="LineNumber" type="xsd:int"/>
         <xsd:element name="ColumnNumber" type="xsd:int"/>
      </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="ValidationReport" type="ValidationReportType"/>
</xsd:schema>

=== cessda/cessda.cmv.core/src/test/resources/eu.cessda.cmv.core.mediatype.validationreport.ValidationReportTest/eclipselink-moxy.xml
<?xml version="1.0" encoding="UTF-8"?>
<ValidationReport
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="cmv:validation-report:v0 https://raw.githubusercontent.com/cessda/cessda.cmv.core/stable/schema/validation-report-v0.1.xsd" xmlns="cmv:validation-report:v0">
	<DocumentUri>urn:uuid:00000000-0000-0000-0000-000000000000</DocumentUri>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:subject/ddi:topcClas/@vocab' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:subject/ddi:topcClas/@vocabURI' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'./@event' is mandatory in /ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:collDate</Message>
		<LocationInfo>
			<LineNumber>74</LineNumber>
			<ColumnNumber>33</ColumnNumber>
		</LocationInfo>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:nation/@abbr' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:anlyUnit/ddi:concept' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:stdyInfo/ddi:sumDscr/ddi:anlyUnit/ddi:concept/@vocab' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:timeMeth/ddi:concept' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:timeMeth/ddi:concept/@vocab' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:sampProc/ddi:concept' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:sampProc/ddi:concept/@vocab' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:collMode/ddi:concept' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:stdyDscr/ddi:method/ddi:dataColl/ddi:collMode/ddi:concept/@vocab' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:fileDscr/ddi:fileTxt/ddi:fileName' is recommended</Message>
	</ConstraintViolation>
	<ConstraintViolation>
		<Message>'/ddi:codeBook/ddi:fileDscr/ddi:fileTxt/ddi:fileName/@xml:lang' is recommended</Message>
	</ConstraintViolation>
</ValidationReport>
